### ISSUE TITLE
Register as Jobseeker but still able to login as Employer

### ISSUE THREAD

**Issue by Wyfy0107** [Integrify-Team-4/Tindev#84]
If you go to our frontend and register as a jobseeker, then login as an employer will still response with 200

**Comment by dilippoudel** [comment]
I tried this one with postman;
first sign up as jobseeker `https://tindev-dev-deploy.herokuapp.com/jobSeeker`
and log in with that credential `https://tindev-dev-deploy.herokuapp.com/employer`
response as a message `email already exists`, 
if it happens as you found the issue, i think its because of client side, not the server side.
so; could you please check once?

**Comment by Wyfy0107** [comment]
You can try registering with only credential, then login with it, see what the response look like

**Comment by dilippoudel** [comment]
Solved

**Comment by dilippoudel** [comment]
solved
